### ISSUE TITLE
Explain some things better at the beginning of the course

### ISSUE THREAD

**Issue by DavidWhitlock** [DavidWhitlock/PortlandStateJava#242]
Putting together the screencast of debugging the web application project made me realize that there are some topics and concepts in the Advanced Programming with Java course that I could explain better.  I'd like to to use this GitHub issue to capture a list of things that I need to more effectively explain and document to make the course more accessible and help students focus on the interesting parts of the course (writing code) and less on things that are annoying or wasteful (setting up their environment, maybe?).

So, what should I explain better next time?

**Comment by natreed** [comment]
The screen casts on YouTube were a great resource with good step by step instructions, but I missed the mention of them in the first lecture and learned about them a week and a half later. Consequently, I spent way too much time trying to get the environment up and running.  The run-through of the setup and testing in class moved too quickly to be useful to me. The documentation left out some key steps like setting up maven and Java10 globally for those who haven't had lots of experience playing with $PATH. The nuts and bolts of the integrated testing were lost on me the first lecture because I was fighting with the setup. Spending so much time with the setup took away from time I could have spent working on the project. 

My suggestion would be to produce a more detailed sheet of written instructions and walk through them the first half of the first lecture, to try to get everyone's environment set up. This would include downloading the correct version of Intellij, where to store maven, how to get everything set up globally on the system. This will cut into teaching time, but I believe if you had people divide up into groups of four and help each other with the setup it would go more quickly. You could even go further and group people by Operating System as well. Finally, an exercise where we could write tests for our first class in the project together to get everyone pointed in the right direction. The tradeoff might be adding some more requirements like a list of tests to write for the command line parser and/or adding a class to project1.

**Comment by DavidWhitlock** [comment]
For Summer 2019, I've put together the https://github.com/DavidWhitlock/PortlandStateJavaGettingStarted repository.  I hope that helps makes the class more accessible at the beginning.

**Comment by DavidWhitlock** [comment]
I used the "Getting Started" repository a couple of time now and it's worked well.  Issue #144 added the Maven wrapper to the projects which has also made it easier for student to get started.  There might be more specific requests in the future, but for now, I'm going to call this issue closed.
